ROLE_CUSTOMER = "customer"
ROLE_SHOPKEEPER = "shopkeeper"
ROLE_ADMIN = "admin"
ROLE_SUPER_ADMIN = "super_admin"
ADMIN_ROLES = (ROLE_ADMIN, ROLE_SUPER_ADMIN)

STATUS_PLACED = "placed"
STATUS_ACCEPTED = "accepted"
STATUS_REJECTED = "rejected"
STATUS_PREPARING = "preparing"
STATUS_OUT_FOR_DELIVERY = "out_for_delivery"
STATUS_DELIVERED = "delivered"
STATUS_CANCELLED = "cancelled"

ACTIVE_ORDER_STATUSES = (STATUS_PLACED, STATUS_ACCEPTED, STATUS_PREPARING, STATUS_OUT_FOR_DELIVERY)

# Which status the SHOPKEEPER may move an order to, from its current status.
SHOPKEEPER_STATUS_TRANSITIONS: dict[str, set[str]] = {
    STATUS_PLACED: {STATUS_ACCEPTED, STATUS_REJECTED},
    STATUS_ACCEPTED: {STATUS_PREPARING},
    STATUS_PREPARING: {STATUS_OUT_FOR_DELIVERY},
    STATUS_OUT_FOR_DELIVERY: {STATUS_DELIVERED},
}

SHOP_STATUS_PENDING = "pending"
SHOP_STATUS_APPROVED = "approved"
SHOP_STATUS_REJECTED = "rejected"
